[package]
name = "alice_os"
version = "0.1.0"
authors = ["Tiago Deliberali <tiago.deliberali@gmail.com>"]
edition = "2018"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies]
bootloader = "0.9.2"
volatile = "0.2.6"
spin = "0.5.2"